anguage: cpp
compiler: gcc
dist: xenial

before_install:
    # C++14
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    # Qt 5.11
    - sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y
    - sudo apt-get update -qq

install:
    # System Dependencies
    - sudo apt-get install build-essential libgl1-mesa-dev
    # C++14
    - sudo apt-get install -qq gcc-7 g++-7
    # Qt 5.11
    - sudo apt-get install -qq qt511base qt511webchannel qt511webengine
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    - source /opt/qt5*/bin/qt5*-env.sh

script:
    # Build
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4
      
    # Prepare
    - mkdir deploy
    - cp LibREDasm.so deploy/
    - cp REDasm deploy/

    # Database
    - cd deploy
    - git clone https://github.com/REDasmOrg/REDasm-Database.git database
    - rm -rf database/.git

    # Deploy
    - sh ../ci/deploy.sh

notifications:
    email: false
