anguage: cpp
compiler: gcc
dist: trusty

before_install:
    # C++14
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    # Qt 5.6
    - sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y
    - sudo apt-get update -qq

install:
    # C++14
    - sudo apt-get install -qq gcc-7 g++-7
    # Qt 5.11
    - sudo apt-get install -qq qt511base
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    - source /opt/qt5*/bin/qt5*-env.sh

script:
    # show OS/compiler version
    - uname -a
    - $CXX --version
    # compile...
    - mkdir build
    - cp -r database/ build/database/
    - cd build
    - qmake PREFIX=/usr ..
    - make -j4
    - sh ../ci/deploy.sh

notifications:
    email: false
