version: "{build}"

branches:
  only: 
    - master

init:
- ps: Update-AppveyorBuild -Version "REDasm_Windows_i686_$(Get-Date -format ddMMyyyy)_$env:appveyor_build_number"

environment:
  build_repo: REDasm-Builds
  github_token:
    secure: 6L5tNTkn5rK+d7vU1DvsIE2LvLu7KkxPoaq2ja+SjlQn37iEU/YnzjmXU15IDu17

skip_tags: true
max_jobs: 4

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.9.2\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%
  # Get rid of sh.exe
  # - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%.

build_script:
  - g++ --version
  - mingw32-make --version
  - mkdir build
  - xcopy database build\database\ /E
  - cd build
  - qmake CONFIG+=release ..
  - mingw32-make -j4
  - ps: ../ci/package.ps1
  - ps: ../ci/deploy.ps1