version: "{build}"
image: Visual Studio 2017

branches:
  only: 
    - master

init:
- ps: Update-AppveyorBuild -Version "REDasm_Windows_x86_64_$(Get-Date -format ddMMyyyy)_$env:appveyor_build_number"
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  build_repo: REDasm-Builds
  deploy_destination:
    secure: 2MDeXDVdvbgID1LEIO1SDXfW9+a4IyhjiZe3g3U+nvgM9t+kVhYr++H4bxH0/IKW
  deploy_token:
    secure: giPdvy7agNmC63x+dxFDtRQue4aC4eqDL34N6/I6igkAv8Bkt9K981waPl3OO1AxkJaIi3nMrpoFDEMoBrHR1AHc0MQjjYwoj3vtdBNfgpbmQJcInZo+uQB90dR/i85piZPdzEQ3m8N5dPDYZ1dKJIO6etv/5NyrBRxLpmzn9aCVxagPPJUHS1+W8u/yNe1fVq7T/Eo2Yl1Aon/3itdMtjn6z9GMfq5A34zfjdB8Voy1mtuBeMC7QpCFUI15M4r9dDMxmBRgvwnKkDXjmr6RUJnFwD8noekYt6ixCC9FCWa1VHOzfMAbTO8bw3K5ZSNA7Lk8+3dOQcff8qopglfcOg033UV4e0dnBnmHq2jW0Fav20xQG6BG+Aw34WjgnyM7Mg+6WdTTvQGtDt9KhxclCUw56bl/HpUDZ2XacrHYKWT/HyxJnex6/3R+eNOhobRhBUZhzAstviESWBDpJfxPe7Fs9oiIXviwaKjoTpgOckTTxdOPdz6jXFortCMW2C+N9/ihHvJ5FMXPDCqopyC643gs9zpoTLZDnD17XdGZNao4D3m5QrL+8bYVZQTR+BI/GPPqQMOoXg+fktd30LGIfq+h688N/ELXg/ddF18Z+cTHOL7S1ZJI8kSfApa7ZX/42HmsqkycCl2gZTUCrLjkyGFjWF7ThCcvBiripLXjmxQFN5MneZ2Ke5Lh2J5GrmSI5JKsxuSLMSpDpd5DREG/3uvaMnz+LrNJbg0zNSGpWOU+tAsO93oOovp+rjK/N4xZAkPGBD6PhzziKS6gIwYX7MH8CYGMDwp+1qNB04tb4sWSDDyRtQfHFdbhXD5HyNZn2BDl7Rc8lD4WTUe9sP+wGjW5TTXOqMw7rViOnQ+sBtgmsAxEtUiJkiJIEJsFoI2qeQ2S2RLBkGrhhK8/Fgp7qYJEF6qqmegpi7tykjFWoFUf8nwceH7st8N2fpNJ7e+InzD13lLJz1td32IuiUS9BP5xgHKuNxe9Dqiz3hl93lETLaL0Ow9JHW62z4E0XRUvCqCaU+rjryLEI+F3fkGa7zkVw7s7ROC/zRez3BWib3qlRDYSNiexer4ScK29EflkIrOPAIDjbIxe1gH4SdOU7ZGo7wPbFThqKdOxmBEzDU70i+OhqB/HQlcPsuZhYfmJvyCBbzqiYJu9Pz6w1w2SrCKsDSc5WE9vp8CLXg+kzh8U8fNVa+l5JfSumJ+yqiBBDsiyugOSreowkw9RxUV7VjRNFvhbYFo0Y9B2wp3n+KnoPCuBEOcY+23TaslCd7b+mhVOLFMUAbFxexV3SW97702vRfdpOVX0GRqpyo3i5H8NRwdkobmbvae6wht1jN/25s2Q00xCShGUC8rjw3RWxNeXLGMeXuTYxy+02/UcBzQbSmmqn/aicQ/oQFPPP4L3EHMEkHGg/i8uG7Jj+p+lteXLKOtPNbd9cAVPQWUdmwvN0NZx0lYH8fMvoEseNc1niyrBOdXwbcIEWp8848LGtW9kSAXKkFYyd0vHTpzLLCRymzKXCTks7X2XnRQi/g2sSbIAQ6zFidY6ro/MmLA6eilyTgGVudt8Qw0IUWxr1dsrV9ETWQEC6vdb3WItR/0dmD8p21UQmmqBiGMUiJ8FD2lKfHb3K1WinYeV+YRuqFbshmfdZg46gGSeBE4Kjy6Fh8Jv3d3HxgK9ltEGNtK48HKpe8LALngZFNW6eKPpyeqzU11HSR8POQLsY6qcbsj4qMMt+V4oDErw+SG/fMgSEOrKdnQDDU/VKnXIRhIG4cgubyBUdFcXLI5/z2ZKhZK2Bb3U37uR3SQ+MG6VoZRXjaK1GOkALAZbqfjm3OFxz0t48IbNXiEMY+7J9BXHyTntBcsiCGS3RNGXRcAjrRz/LoN3LhySRqJ+5UbN/oEHNqu6xfrQ+wnoHB6iwxVXbdyOjD0/QeQEmnj3f/s9tcyzmiuK+ZxHzJqVHfwtZcyEdevW/Ujf1adC7IiH3u8wVe583mM4/tqQ98wZIxlRldYQp610w44OaKGqanhYGKN35wyUKdfiIXiq0Qq2ISkyoSiaVjxa1fdMj4NHeWKQKVWyISlNd1nFvM9k4d9fBlBvNxz2xTpv3mNp7pgUbOWyJFPY47DAjG+NUqPOnT6NHanwaGVebXJ70NT12t2C7rxxH/LFDw2E+MutjBl+zqvs/EAWZZ89lTKyOmE21w+dxkJJt9Lobp9bs6CVc7moqI6NHeZ3PW4Kma55CtLTmsxgl19NWnT0Bud4jCEvJVdlfdVS2Z5cOcnqOnpu55LLKkPu5MDPkpqHt8UBJzPjdHdiJOp8CtgQi3bHRy/AGlUhNS1x+v1FJYhanoMwXObkBEBC3EqnwgvHAS2UmNDG125Ve+QPQ+rtX0u1Ky76+r05HyYVgWOWmiwdGXdmv4PMYfNWv9EOk2WrctA2GrWpOJgD/LDo

skip_tags: true

install:
  - git submodule update --init --recursive
  - set QTCREATOR=C:\Qt\Tools\QtCreator\bin
  - set QTDIR=C:\Qt\5.11\msvc2017_64\bin
  - set PYTHONDIR=C:\Python37-x64
  - set PATH=%QTDIR%;%QTCREATOR%;%PYTHONDIR%;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  # Build
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
  - jom -j4

  # Package & Deploy
  - python ../ci/package.py
  - python ../ci/deploy.py
