version: "{build}"
image: Visual Studio 2017

branches:
  only: 
    - master

init:
- ps: Update-AppveyorBuild -Version "REDasm_Windows_x86_64_$(Get-Date -format ddMMyyyy)_$env:appveyor_build_number"

environment:
  build_repo: REDasm-Builds
  github_token:
    secure: 6L5tNTkn5rK+d7vU1DvsIE2LvLu7KkxPoaq2ja+SjlQn37iEU/YnzjmXU15IDu17

skip_tags: true

install:
  - git submodule update --init
  - set QTCREATOR=C:\Qt\Tools\QtCreator\bin
  - set QTDIR=C:\Qt\5.11\msvc2017_64\bin
  - set PATH=%QTDIR%;%QTCREATOR%;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  # Build
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
  - jom -j4

  # Prepare
  - mkdir deploy
  - xcopy LibREDasm.dll deploy
  - xcopy REDasm.exe deploy
  - cd deploy
  - windeployqt --release .

  # Database
  - git clone https://github.com/REDasmOrg/REDasm-Database.git database
  - del /Q database\.git

  # Deploy
  - ps: ../../ci/deploy.ps1
